Fix/901/excluding last building error b
MaibornWolff/codecharta pull request #1894
Opened 2021-03-24 17:36 UTC by Jacob-Kirimi

excluding last building error

Excluding the last building on the map results in an error, reincluding the buildings makes them all the same size.Console Error after last building is excluded, Error in Building Size and Color afterwards if buildings are included again

closes #901

Expected Behavior
When the user excludes the last building the map is empty, reincluded buildings look the same as before exclusion.

Actual Behavior
When the user excludes the last building on the map a console error is thrown, reincluding buidlings afterwards results in all of them being color, due to the metric switching to unary

2021-03-24 17:44 UTC, Jacob-Kirimi commented
@BridgeAR  remaining is a small clarification on the behaviour once all is excluded. to disable search input or eliminate a condition that is not fullfilled if someone tries to search at this point or alternatively do both.

2021-04-15 15:22 UTC, NearW commented on visualization/app/codeCharta/ui/searchBar/searchBar.po.ts
> +		await page.waitForTimeout(500)
```suggestion
		await page.waitForSelector("#blacklistMenu.md-clickable")
```

2021-04-15 15:25 UTC, NearW commented on visualization/app/codeCharta/ui/dialog/dialog.globalSettings.po.ts
> +		await page.waitForSelector(".md-select-menu-container.md-active", { visible: true })
```suggestion
		await page.waitForSelector(".md-select-menu-container.md-clickable")
```

clickable is better than md-active.

2021-04-19 09:04 UTC, Jacob-Kirimi commented on visualization/app/codeCharta/ui/dialog/dialog.globalSettings.po.ts
> +		await page.waitForSelector(".md-select-menu-container.md-active", { visible: true })
done

2021-04-30 09:24 UTC, BridgeAR commented
Supersedes #1152

2021-05-03 00:32 UTC, Med-H requested changes

2021-05-03 00:32 UTC, Med-H commented on visualization/app/codeCharta/util/dataMocks.ts
> +			link: "http://www.google.de"
```suggestion
			link: "https://www.google.de"
```

2021-05-21 10:06 UTC, BridgeAR commented
Due to the many conflicts it's easier to close this and to open a new PR to address this issue. Thanks for the great work though!

2021-05-21 10:06 UTC, closed without merging