Refactor/2318/migrate sorting option component
MaibornWolff/codecharta pull request #2472
Opened 2021-10-30 13:13 UTC by shaman-apprentice

refs: #2318
Resolve #2107

2021-10-30 16:49 UTC, shaman-apprentice commented
Sonar is red due to "less than 80% test coverage" - all uncovered lines are `NgModule` := import overhead and can safely be ignored. So I declare the pipeline as green 😎

2021-11-02 10:12 UTC, jannikr requested changes
If I understand correctly, the Sorting Option function is responsible for sorting the project folders in the File/Node Explorer. However, I noticed here that sorting by name does not work.
<img width="570" alt="sorting-option" src="https://user-images.githubusercontent.com/31436472/139827391-cf16bebe-6c8f-4d44-b912-93419758eb51.png">

2021-11-02 12:20 UTC, shaman-apprentice commented
> If I understand correctly, the Sorting Option function is responsible for sorting the project folders in the File/Node Explorer. However, I noticed here that sorting option has a different behavior. <img alt="sorting-option" width="570" src="https://user-images.githubusercontent.com/31436472/139827391-cf16bebe-6c8f-4d44-b912-93419758eb51.png">
> 
> **Setup:** Node v16.12.0 MacOs using Chrome v95.0.4638.54

Good catch. This is currently a bug in released version, that it displays wrong title. I will change the tooltip instead of the sorting order and fix with it #2473.

2021-11-03 11:03 UTC, jannikr approved these changes

2021-11-03 11:10 UTC, merged