Fix compatibility md5 with url query #2493
MaibornWolff/codecharta pull request #2494
Opened 2021-11-09 16:21 UTC by Shivan-997

# Fix compatibility md5 with Url query

closes: #2493

2021-11-09 16:21 UTC, jannikr approved these changes

2021-11-09 16:30 UTC, ce-bo requested changes
Please write a regression test.

2021-11-09 20:01 UTC, BridgeAR approved these changes
LGTM with a test.

2021-11-10 09:29 UTC, ce-bo approved these changes

2021-11-10 11:18 UTC, IhsenBouallegue approved these changes

2021-11-10 11:33 UTC, merged