Refactor/2318/improve custom dispatch
MaibornWolff/codecharta pull request #2614
Opened 2022-01-19 18:10 UTC by shaman-apprentice

2022-01-19 18:40 UTC, shaman-apprentice commented on visualization/app/codeCharta/state/effects/unfocusNodesOnLoadingMap.effect.ts
> +			filter(action => isActionOfType(action.type, IsLoadingFileActions)),
This is the previous behavior. Is this really wanted? At least only unfocus when the payload was set to `true`?

2022-01-24 07:26 UTC, IhsenBouallegue requested changes
LGTM 🥳
Just fixed the changelog entry.

2022-01-24 07:26 UTC, IhsenBouallegue commented on CHANGELOG.md
> +    - Only unfocus focused node when map starts to load and not as well when map has finished loading. This shouldn't change any behavior for the user.
```suggestion
    - Unfocus focused node only when map starts to load and not also when map has finished loading. This shouldn't change any behavior for the user [#2614](https://github.com/MaibornWolff/codecharta/pull/2614)
```

2022-01-26 07:16 UTC, IhsenBouallegue approved these changes

2022-01-26 07:49 UTC, merged