Feature/2499/show garbage bin next to the loaded maps
MaibornWolff/codecharta pull request #2647
Opened 2022-02-08 10:22 UTC by Shivan-997

# show garbage bin next to the loaded maps

closes: #2499 

## Screenshots or gifs
<img width="391" alt="image" src="https://user-images.githubusercontent.com/57844849/152967777-1fd42bd7-a20c-4570-8c24-7fe94222f577.png">

2022-02-08 10:23 UTC, Shivan-997 commented
i am not sure if it is the best solution to just disable button when only one map left.

2022-02-08 16:29 UTC, cschild commented on visualization/app/codeCharta/ui/filePanel/filePanelFileSelector/filePanelFileSelector.component.html
> +			[files]="files"
we could test the number of files here *ngIf="files.length > 1", thus the delete button wouldn't apear

2022-02-14 08:12 UTC, Christian-Eberhard requested changes

2022-02-14 08:12 UTC, Christian-Eberhard commented on visualization/app/codeCharta/ui/filePanel/filePanelFileSelector/filePanelFileSelector.component.scss
> +	display: flex !important;
!important is evil, try beeing more specific with the selector instead.

2022-02-14 08:12 UTC, Christian-Eberhard commented on visualization/app/codeCharta/ui/filePanel/filePanelFileSelector/removeFileButton/removeFileButton.component.html
> +	<span class="symbol"><i class="fa fa-trash delete-symbol"></i></span>
Is there a reason for the span? Maybe just give the <i> the class "symbol"

2022-02-14 11:22 UTC, Christian-Eberhard approved these changes

2022-02-14 12:19 UTC, merged