Refactor/2489/Migrate add custom config button in ribbonbar
MaibornWolff/codecharta pull request #2736
Opened 2022-03-20 17:42 UTC by Hall-Ma

# Migrate 'Add' button for Custom Views in ribbon bar

Ref: #2489, #2318

2022-03-20 20:19 UTC, shaman-apprentice requested changes
I think we should re-add some whitespace to the right. I think giving the two buttons from custom views the same width and whitespaces as the suspicious metrics would be nice?
![image](https://user-images.githubusercontent.com/3596742/159184159-0c836a08-ae78-4a37-ac35-28b30b161fc0.png)

Beside those little things awesome work 👍  This PR will be the first checked checkbox from #2318 not by me 🙂😍

2022-03-20 20:19 UTC, shaman-apprentice commented on visualization/app/codeCharta/ui/customConfigs/customConfigs.component.scss
>  .custom-configs {
We can remove the empty selector (as suggested by [sonar's detected code smell](https://sonarcloud.io/project/issues?id=maibornwolff-gmbh_codecharta_visualization&pullRequest=2736&resolved=false&types=CODE_SMELL))

2022-03-20 20:19 UTC, shaman-apprentice commented on visualization/app/codeCharta/ui/customConfigs/customConfigs.component.scss
> +	width: calc(50% - 2.5px);
do we need this expensive `calc`? I would prefer alignment with flex or to just hard code some pixel width

2022-03-20 20:20 UTC, shaman-apprentice commented
As the ui is slightly changed, we should probably add an changelog entry.

2022-03-21 11:57 UTC, Christian-Eberhard approved these changes
Looks good to me, only the "white-space" issue remains

2022-03-21 12:13 UTC, shaman-apprentice approved these changes

2022-03-21 12:32 UTC, merged

2022-03-21 12:39 UTC, IhsenBouallegue commented
Does this issue have a changelog entry?