Fix installation description for Apple Silicon #2955
MaibornWolff/codecharta pull request #2956
Opened 2022-08-05 13:01 UTC by stultiloquence

# Fix installation description for Apple Silicon

Fixes Issue: #2955

2022-08-05 14:26 UTC, jannikr approved these changes

2022-08-05 18:16 UTC, BridgeAR approved these changes

2022-08-05 18:17 UTC, BridgeAR requested changes

2022-08-05 18:17 UTC, BridgeAR commented on README.md
> +-   **Local:** See [here](visualization/readme.md).
```suggestion
-   **Local:** See [here](visualization/README.md).
```

2022-08-05 18:18 UTC, BridgeAR commented on README.md
> +-   **Local:** See [here](visualization/readme.md).
Linux is not lenient when it comes to caps / no caps.

2022-08-09 08:28 UTC, ce-bo approved these changes
LGTM

2022-08-09 09:47 UTC, jannikr commented
Merge with branch protection bypass due to a missing Sonar token in the forked repository. It should be possible to merge successfully as there are only changes in the Readme.md files.

2022-08-09 09:52 UTC, merged