Update package list before install of wine #2975
MaibornWolff/codecharta pull request #2976
Opened 2022-08-10 14:41 UTC by jannikr

# Update package list before install of wine

Issue: #2975

2022-08-10 14:50 UTC, MW-Friedrich approved these changes
LGTM!

2022-08-10 14:52 UTC, MW-Friedrich requested changes

2022-08-10 14:52 UTC, MW-Friedrich commented on .github/workflows/release_gh_pages.yml
> +          sudo apt update
Maybe use apt-get instead, since apt does not have a stable cli interface
```suggestion
          sudo apt-get update
```

2022-08-10 14:56 UTC, MW-Friedrich approved these changes

2022-08-10 15:15 UTC, merged

2022-08-11 07:04 UTC, ce-bo commented
The referenced issue is not closed, although the PR has been merged. To close issues automatically on merge, just update the PR description from "Issue #2975" to "Close #2975".