Fix/3406/fix rawtextparser input handling 1
MaibornWolff/codecharta pull request #3415
Opened 2023-11-21 15:43 UTC by fritschldwg

# Fix/3406/fix rawtextparser input handling 1

Issue: #3406

## Description
- When an empty string is provided as the value for the 'metrics,' 'file-extensions,' or 'exclude' flag, the rawtextparser now correctly handles these inputs by filtering out the empty strings.

## Definition of Done

A PR is only ready for merge once all the following acceptance criteria are fulfilled:
- [ ] Changes have been manually tested
- [ ] All TODOs related to this PR have been closed
- [ ] There are automated tests for newly written code and bug fixes
- [ ] All bugs discovered while working on this PR have been submitted as issues (if not already an open issue)
- [ ] Documentation (GH-pages, analysis/visualisation READMEs, parser READMEs, --help, etc.) has been updated (almost always necessary except for bug fixes)
- [ ] CHANGELOG.md has been updated

2023-11-22 09:47 UTC, ce-bo commented
Would you please add the link to this PR on the related bullet point within the issue?

2023-11-22 09:50 UTC, ce-bo commented on analysis/model/src/main/kotlin/de/maibornwolff/codecharta/util/StringToListInputConverter.kt
> +class StringToListInputConverter : CommandLine.ITypeConverter<List<String>> {
```suggestion
class CommaSeparatedStringToListConverter : CommandLine.ITypeConverter<List<String>> {
```

2023-11-22 09:55 UTC, phanlezz requested changes

2023-11-22 09:55 UTC, phanlezz commented on analysis/parser/RawTextParser/src/test/kotlin/de/maibornwolff/codecharta/rawtextparser/MetricCollectorTest.kt
> +    fun `Should exlude regex patterns`() {
```suggestion
    fun `Should exclude regex patterns`() {
```

2023-11-22 09:55 UTC, phanlezz commented on analysis/parser/RawTextParser/src/test/kotlin/de/maibornwolff/codecharta/rawtextparser/MetricCollectorTest.kt
> +    fun `Should include only spedified File extensions`() {
```suggestion
    fun `Should include only specified File extensions`() {
```

2023-11-22 10:03 UTC, ce-bo commented on analysis/parser/RawTextParser/build.gradle
> +    implementation project(path: ':import:SourceCodeParser')
This should not be needed.
Dependencies between parsers should be avoided if there is no good reason for it.

2023-11-22 11:01 UTC, Nereboss commented
> I'm getting this error if I try to parse the codecharta directory: ![grafik](https://user-images.githubusercontent.com/65733509/284863178-ddea1d47-be89-4269-a249-43d703f00a50.png) Ignore the double line for regex (I was resizing the window)
> 
> Edit: There might be a mistake in my call, if so, ignore this :)
> 
> I tried to only parse`.kt`files, but got the same problem: ![grafik](https://user-images.githubusercontent.com/65733509/284863549-0ecb2db1-86c3-4b87-a7a5-974ea88843b9.png)

We are aware of this error, it is planned that it is not addressed in this PR as it is caused by the max-indentation-level flag will be fixed in a future PR of this bigger issue. If you paste the command the interactive mode gave you and remove the max-indentation-level flag then everything should work (at least it does in my machine)

2023-11-24 08:02 UTC, phanlezz approved these changes

2023-11-24 08:02 UTC, merged